name: canvas-peer-reviews
channels:
    - conda-forge
    - anaconda
    - defaults
dependencies:
    - termcolor
    - python>=3.7.0
    - colorama
    - requests
    - jupyter
    - pandas
    - pip
    - pip:
          - canvasapi>=2.0.0
          - pick
